services:
  frontend:
    image: ghcr.io/profiidev/images/node-alpine-dev:main
    restart: unless-stopped
    volumes:
      - ./frontend:/app/frontend
      - ./node_modules:/app/node_modules
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
    tty: true
    ports:
      - '5174:5174'
    networks:
      - nginx
    working_dir: /app/frontend
    command: npm run dev -- --host
    #command: npm i

  backend:
    image: ghcr.io/profiidev/images/rust-musl-watch:main
    restart: unless-stopped
    volumes:
      - ./.cargo:/app/.cargo
      - ./backend:/app
      - ./shared:/shared
    networks:
      - nginx
    tty: true
    ports:
      - '5173:8000'
    entrypoint: ['tini', '--']
    command: ['cargo', 'watch', '-x', 'run']
    depends_on:
      postgres:
        condition: service_healthy

  wings:
    image: ghcr.io/profiidev/images/rust-musl-watch:main
    restart: unless-stopped
    volumes:
      - ./wings:/app
      - ./shared:/shared
    networks:
      - nginx
    tty: true
    ports:
      - '8123:8000'
    entrypoint: ['tini', '--']
    command: ['cargo', 'watch', '-x', 'run']

  postgres:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    networks:
      - nginx
    ports:
      - '9301:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'test']
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 1s

networks:
  nginx:

volumes:
  logs:
