[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
centaurus = { version = "0.4.7", default-features = false, features = [
  "error",
] }
chrono = "0.4.43"
hex = "0.4.3"
hmac = "0.12.1"
http = "1.4.0"
rand = "0.9.2"
sha3 = "0.10.8"

[lib]
path = "src/lib.rs"
